---
- name: Install apache and modules
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - php5-cli
    - apache2
    - php5-cgi
    - php5
    - libapache2-mod-php5
    - libapache2-mod-webauthldap

- name: Install decode-user
  copy:
    src: roles/web/files/decode-user 
    dest: /usr/local/bin/decode-user
    owner: root
    group: root
    mode: 0755
  
