---
- name: Microsites playbook
  hosts: vagrant
  remote_user: vagrant
  become: yes
  roles:
    - role: standard
      tags: ['vagrant']
    - role: database
      tags: ['vagrant']
    - role: web
      tags: ['vagrant']
    - role: sites
      tags: ['vagrant']
  vars:
    vagrant: true
    sites:
      - exhibits
